export const data = [
  {
    id: 1,
    title: "Tea Time",
    desc: "Dev Academy Bootcamp Final Project. Group work with four other amazing people to create a MVP in 1 week. Automated solution to pick your favourite recipes for the week and generate a shopping list to buy all the ingrediants",
    tech: ["React", "Redux", "Express", "Knex", "Postgres/Sqlite3", "Jest"],
    images: ["/img/teatime0.png", "/img/teatime1.png", "/img/teatime2.png", "/img/teatime3.png", "/img/teatime4.png"],
    link: "",
    video: "https://www.youtube.com/watch?v=ejJew8nsYeY",
    tags: ["all", "group", "database"],
    color: "radial-gradient(circle, rgba(220,38,38,1) 0%, rgba(251,191,36,1) 100%)"
  },
  {
    id: 2,
    title: "Developer.Blog",
    desc: "This is a personal project developed as part of my portfolio project to show potential employers",
    tech: ["Next.js", "Redux", "Prisma", "Postgres/Sqlite3", "Draft.js", "React-hook-form"],
    link: "https://blog-jamesprenticez.vercel.app/",
    video: "",
    images: ["/img/blog0.png", "/img/blog1.png", "/img/blog2.png", "/img/blog3.png", "/img/blog4.png", "/img/blog5.png", "/img/blog6.png",  "/img/blog7.png",],
    tags: ["all", "hobby", "blog", "authentication"],
    color: "radial-gradient(circle, rgba(255,0,255,1) 0%, rgba(171,0,255,1) 83%)"
  },
  {
    id: 3,
    title: "Egyptian NFT's",
    desc: "Mint a hero and fight the boss in a turn based card game https://rinkeby.etherscan.io/address/0x4b8A189189f8c1d3B3E7bDE7E6B32004580D3889 https://testnets.opensea.io/assets/0x4b8A189189f8c1d3B3E7bDE7E6B32004580D3889/1",
    tech: ["Next.js", "Solidity", "Hardhat", "Open Zeppelin", "Ethers", "Rinkeby Testnet"],
    images: ["/img/egyptian0.png", "/img/egyptian1.png", "/img/egyptian2.png", "/img/egyptian3.png", "/img/egyptian4.png", "/img/egyptian5.png"],
    link: "",
    video: "",
    tags: ["all", "hobby", "crypto"],
    color: "radial-gradient(circle, rgba(220,38,38,1) 0%, rgba(251,191,36,1) 100%)"
  },
  {
    id: 4,
    title: "SelfRegulator",
    desc: "Habit Tracking to do list with agregated data and statistics for the entire year",
    tech: ["Next.js", "Redux", "Prisma", "Postgres/Sqlite3", "Moment"],
    link: "https://selfregulator-jamesprenticez.vercel.app/",
    video: "",
    images: ["/img/selfregulator0.png"],
    tags: ["all", "database", "authentication"],
    color: "radial-gradient(circle, rgba(0,255,29,1) 0%, rgba(159,255,0,1) 100%)",
  },
  {
    id: 5,
    title: "Instagram Clone",
    desc: "Post photos and have your friends like and comment", 
    tech: ["Next.js", "Redux", "Prisma", "Postgres/Sqlite3", "Firebase"],
    link: "",
    video: "",
    images: ["/img/default.png"],
    tags: ["all", "clone"],
    color: "radial-gradient(circle at 30% 107%, #fdf497 0%, #fdf497 5%, #fd5949 45%,#d6249f 60%,#285AEB 90%)",
  },
  {
    id: 6,
    title: "Google Doc's Clone",
    desc: "Rich text editor in the cloud",
    tech: ["Next.js", "Redux", "Prisma", "Postgres/Sqlite3", "Draft.js"],
    link: "",
    video: "",
    images: ["/img/googledocs0.png", "/img/googledocs1.png"],
    tags: ["all", "clone"],
    color: "radial-gradient(circle, rgba(37,99,235,1) 0%, rgba(56,189,248,1) 100%)"
  },
  {
    id: 7,
    title: "Spotify Clone",
    desc: "Create and share music playlists",
    tech: ["Next.js", "Redux", "Spotify API"],
    link: "",
    video: "",
    images: ["/img/default.png"],
    tags: ["all", "clone"],
    color: "radial-gradient(circle, rgba(29,185,84,1) 0%, rgba(29,161,185,1) 92%)"
  },
  {
    id: 8,
    title: "Repeat Use",
    desc: "Ecommerce Store for reuable product to help mitigate the impact of single use product on the enviroment",
    tech: ["Next.js"],
    link: "",
    video: "",
    images: ["/img/default.png"],
    tags: ["all", "hobby", "ecommerce"],
    color: "radial-gradient(circle, rgba(255,0,255,1) 0%, rgba(171,0,255,1) 83%)"
  },
]